#!/usr/bin/env bash
# ssh config file
Host *
      PasswordAuthentication no
      IdentifyFile ~/.ssh/schhol
      SendENV LANG LC_*
      HashKnownHosts yes
      GSSAPIAuthentification yes
      GSSAPIDelegateCredentials no
